FROM mcr.microsoft.com/powershell:lts-nanoserver-1903

ADD installer/pyth-windows.zip .

RUN pwsh -Command \
	Expand-Archive -LiteralPath C:\pyth-windows.zip -DestinationPath C:\ ; \
	Remove-Item C:\pyth-windows.zip -Force

RUN reg add HKCU\Environment
RUN setx PATH "%PATH%;C:\Python;C:\Python\Scripts\"

CMD ["C:\Python\python.exe"]
